In [1]:
#Python program to interchange first and last elements in a list

In [3]:
li = [20, 50, 62, 32]
li[0], li[-1] = li[-1], li[0]

In [4]:
li

[32, 50, 62, 20]

In [6]:
li= []
for i in range(1, 11):
    li.append(i)
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
import pandas as pd

In [14]:
googleSheetId = '1cVsmSWyoITg70hp6qv2AHlCqCF89mdPqgHUE9DEc9Ok'
sheetName = 'Sheet1'
url = f'https://docs.google.com/spreadsheets/d/{googleSheetId}/gviz/tq?tqx=out:csv&sheet={sheetName}'
df = pd.read_csv(url)

In [16]:
df

email   password   location
0  prathyusha12@gmail.com  prathyu96     kerala
1        john23@gmail.com     john23  hyderabad
2         sai25@gmail.com      sai25      vizag
3      pavani85@gmail.com   pavani85    chennai
4         ram18@gmail.com      ram18  bangalore
5     babitha18@gmail.com  babitha18   tirupati
6     jhanavi26@gmail.com  jhanavi26      vizag

In [38]:
df['email'][0]

'prathyusha12@gmail.com'

In [43]:
var = "pinky68@gmail.com"
df[df['email']!= var]
   

email   password   location
0  prathyusha12@gmail.com  prathyu96     kerala
1        john23@gmail.com     john23  hyderabad
2         sai25@gmail.com      sai25      vizag
3      pavani85@gmail.com   pavani85    chennai
4         ram18@gmail.com      ram18  bangalore
5     babitha18@gmail.com  babitha18   tirupati
6     jhanavi26@gmail.com  jhanavi26      vizag

In [45]:
df1 = df['email']

In [47]:
list(df1)

['prathyusha12@gmail.com',
 'john23@gmail.com',
 'sai25@gmail.com',
 'pavani85@gmail.com',
 'ram18@gmail.com',
 'babitha18@gmail.com',
 'jhanavi26@gmail.com']

In [49]:
st = 'mahesh25@gmail.com'
if st not in list(df1):
    print('invalid email')


invalid email


In [50]:
import numpy as np

In [51]:
li = [1, 2, 3, 4, 5, 6] 
arr = np.array(li)

In [52]:
arr

array([1, 2, 3, 4, 5, 6])

In [60]:
arr1 = np.arange(1, 9).reshape(2,2,2)

In [61]:
arr1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [62]:
arr1.ndim

3

In [63]:
arr1.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
arr1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
arr2 = np.arange(20, 1, -1)
arr2

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2])

In [74]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.33511290e-306]])

In [77]:
x = np.zeros((3, 3), dtype=int)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [78]:
y = np.ones((3,3), dtype=int)
y

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

2

In [80]:
arr[1][2]

6

In [83]:
x = np.ones((5,5), dtype=int)

In [84]:
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [85]:
x.ndim

2

In [88]:
x[1:-1, 1:-1] = 0

In [89]:
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [93]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5,6, 7, 8])
res = np.stack((arr1, arr2), axis=1)

In [94]:
res

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [95]:
np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
np.vstack((arr1, arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
#sorting numpy array
x = np.array([5, 8, 0, 4, 9])
np.sort(x)

array([0, 4, 5, 8, 9])

In [100]:
li = [1, 8, 10, 2, 0, 3, 6]
li.sort()
li

[0, 1, 2, 3, 6, 8, 10]

In [102]:
dic = {'a':10, 'b': 2, 'd': 6, 'c':0}
sorted(dic.values())

[0, 2, 6, 10]