### Feature Transformation

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("../../Downloads/titanic/tested.csv", usecols=['Age','Pclass', 'Fare', 'Survived'])

In [5]:
df.head()

Survived  Pclass   Age     Fare
0         0       3  34.5   7.8292
1         1       3  47.0   7.0000
2         0       2  62.0   9.6875
3         0       3  27.0   8.6625
4         1       3  22.0  12.2875

In [11]:
df['Age'].fillna(df.Age.median(), inplace=True)

In [12]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
Fare        1
dtype: int64

In [13]:
df['Fare'].fillna(df.Fare.median(), inplace=True)

In [14]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
Fare        0
dtype: int64

In [15]:
X = df.iloc[:, 1:]
X

Pclass   Age      Fare
0         3  34.5    7.8292
1         3  47.0    7.0000
2         2  62.0    9.6875
3         3  27.0    8.6625
4         3  22.0   12.2875
..      ...   ...       ...
413       3  27.0    8.0500
414       1  39.0  108.9000
415       3  38.5    7.2500
416       3  27.0    8.0500
417       3  27.0   22.3583

[418 rows x 3 columns]

In [16]:
y = df.iloc[:, 0]

In [17]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [19]:
X_train

Pclass   Age      Fare
41        1  27.0   26.5500
24        1  48.0  262.3750
237       3  20.0    7.2250
309       3  45.0   14.1083
154       3  13.0   31.3875
..      ...   ...       ...
63        3  22.0    7.7250
326       2  12.0   39.0000
337       3  39.0    7.2292
11        1  46.0   26.0000
351       2  25.0   10.5000

[292 rows x 3 columns]

In [20]:
#standardization: we use standardscaler from sklearn library

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)

In [23]:
X_train_scaled

array([[-1.53624848e+00, -2.28510663e-01, -1.18218331e-01],
       [-1.53624848e+00,  1.48360217e+00,  4.23553018e+00],
       [ 8.62599414e-01, -7.99214940e-01, -4.74992167e-01],
       [ 8.62599414e-01,  1.23901462e+00, -3.47914219e-01],
       [ 8.62599414e-01, -1.36991922e+00, -2.89094859e-02],
       [-3.36824533e-01,  9.94427074e-01, -8.37075927e-03],
       [-3.36824533e-01,  8.31368709e-01, -1.28372308e-01],
       [ 8.62599414e-01,  2.60664432e-01, -4.63376017e-01],
       [-3.36824533e-01,  1.60768847e-02, -2.20681192e-01],
       [ 8.62599414e-01, -2.28510663e-01, -4.65299735e-01],
       [ 8.62599414e-01, -4.73098210e-01, -4.65299735e-01],
       [-1.53624848e+00,  1.60768847e-02,  2.18950377e+00],
       [-3.36824533e-01, -5.54627393e-01, -4.14529848e-01],
       [ 8.62599414e-01, -6.36156575e-01, -3.51759807e-01],
       [ 8.62599414e-01, -1.04380249e+00, -4.65608046e-01],
       [-3.36824533e-01,  2.21736481e+00, -3.68375406e-01],
       [-3.36824533e-01,  1.60768847e-02

In [32]:
X_test_scaled = scaler.transform(X_train)

In [33]:
X_test_scaled

array([[-1.53624848e+00, -2.28510663e-01, -1.18218331e-01],
       [-1.53624848e+00,  1.48360217e+00,  4.23553018e+00],
       [ 8.62599414e-01, -7.99214940e-01, -4.74992167e-01],
       [ 8.62599414e-01,  1.23901462e+00, -3.47914219e-01],
       [ 8.62599414e-01, -1.36991922e+00, -2.89094859e-02],
       [-3.36824533e-01,  9.94427074e-01, -8.37075927e-03],
       [-3.36824533e-01,  8.31368709e-01, -1.28372308e-01],
       [ 8.62599414e-01,  2.60664432e-01, -4.63376017e-01],
       [-3.36824533e-01,  1.60768847e-02, -2.20681192e-01],
       [ 8.62599414e-01, -2.28510663e-01, -4.65299735e-01],
       [ 8.62599414e-01, -4.73098210e-01, -4.65299735e-01],
       [-1.53624848e+00,  1.60768847e-02,  2.18950377e+00],
       [-3.36824533e-01, -5.54627393e-01, -4.14529848e-01],
       [ 8.62599414e-01, -6.36156575e-01, -3.51759807e-01],
       [ 8.62599414e-01, -1.04380249e+00, -4.65608046e-01],
       [-3.36824533e-01,  2.21736481e+00, -3.68375406e-01],
       [-3.36824533e-01,  1.60768847e-02

In [26]:
from sklearn.linear_model import LogisticRegression

In [29]:
classification = LogisticRegression()

In [30]:
classification.fit(X_train_scaled, y_train)

LogisticRegression()

In [34]:
classification.predict(X_test_scaled)

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0], dtype=int64)